# Generated by Django 4.2 on 2023-05-07 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_aipost"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Aipost",
        ),
    ]
