# Generated by Django 4.2 on 2023-05-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_text_text_field_1_text_text_field_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image_path",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
