# Generated by Django 4.2 on 2023-05-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aiposts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reporter",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
